kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-persistent-storage
  namespace: rocketchat
  labels:
    type: local
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/disks/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rocketchat-migrate-demo-control-plane
